---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "install nodejs and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: true
  npm:
    name: n
    global: yes
    production: yes

- name: "install nodejs 13.8.0"
  become: true
  shell: |
    curl -sl https://deb.nodesource.com/setup_13.x |sudo -E bash -

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
